# Generated by Django 3.2.13 on 2022-07-07 13:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("django_outbox_pattern", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="received",
            name="msg_id",
            field=models.CharField(max_length=100, null=True),
            preserve_default=False,
        ),
    ]
