# Generated by Django 3.2.13 on 2022-09-10 08:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("django_outbox_pattern", "0002_received_msg_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="published",
            name="version",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
