# Generated by Django 3.2.18 on 2023-04-03 16:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('django_outbox_pattern', '0003_alter_published_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='published',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='msg_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
