# Generated by Django 4.2.14 on 2024-07-15 16:14

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("django_outbox_pattern", "0005_published_headers"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="published",
            index=django.contrib.postgres.indexes.BTreeIndex(fields=["status"], name="published_status_27c9ec_btree"),
        ),
    ]
