# Generated by Django 4.2.14 on 2024-07-15 16:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("django_outbox_pattern", "0005_published_headers"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="published",
            index=models.Index(fields=["status"], name="published_status_27c9ec_btree"),
        ),
    ]
