# Generated by Django 5.1.5 on 2025-10-07 13:57

from django.db import connection
from django.db import migrations
from django.db import models


def add_index_operation(model_name: str, index: models.Index) -> migrations.AddIndex:
    # Get model from model_name usiing django_outbox_pattern as app_label
    if connection.vendor == "postgresql":
        from django.contrib.postgres.operations import AddIndexConcurrently

        return AddIndexConcurrently(
            model_name=model_name,
            index=index,
        )
    return migrations.AddIndex(
        model_name=model_name,
        index=index,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("django_outbox_pattern", "0006_published_published_status_27c9ec_btree"),
    ]

    operations = [
        add_index_operation(
            model_name="received",
            index=models.Index(fields=["status"], name="dop_rec_status_idx"),
        ),
        add_index_operation(
            model_name="received",
            index=models.Index(fields=["added"], name="dop_rec_added_idx"),
        ),
    ]

    def __init__(self, name, app_label):
        super().__init__(name, app_label)
        self.atomic = False if connection.vendor == "postgresql" else True
